// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCabAMtQHXpwfOtsuZ-MYBzF5G8K2eCQQY',
    appId: '1:675022820426:android:999a7ccb98d12edd1802b3',
    messagingSenderId: '675022820426',
    projectId: 'strayconnected-2f0c7',
    storageBucket: 'strayconnected-2f0c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtlHhZpa07BZet93nELtqblNCL5amwEjw',
    appId: '1:675022820426:ios:2c3339a62198ebb81802b3',
    messagingSenderId: '675022820426',
    projectId: 'strayconnected-2f0c7',
    storageBucket: 'strayconnected-2f0c7.firebasestorage.app',
    iosBundleId: 'com.example.strayconnected',
  );

}
